{% set name = "pipe" %}
{% set version = "2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pipe-{{ version }}.tar.gz
  sha256: 6a253198e3bc542ffaf0a4222376586bce8583b27a9ddbc2cfbaa554c049230d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pipe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JulienPalard/Pipe
  summary: Module enablig a sh like infix syntax (using pipes)
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/JulienPalard/Pipe
  dev_url: https://github.com/JulienPalard/Pipe

extra:
  recipe-maintainers:
    - sugatoray
